name: CI

on: [push, pull_request]

jobs:

    pmd:
        name: PMD
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run PMD
                run: ./gradlew pmd

    checkstyle:
        name: Code style
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run checkstyle
                run: ./gradlew checkstyle

    buildRelease:
        name: Release build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run release build
                run: ./gradlew assembleRelease
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token


